<?php 
   include '../../global/dotGlobal_config.inc.php';
?>
<body class="dot_dashboard app-darkmode" id="dot_dashboard">
  <div class="dot_mb_2">
    <h2 class="body_title_sub dot_white font_monts has_icon dot_mb_1">SQL Injection Challenge</h2>
    <h3 class="font_mono dot_no_white dot_f14 l_h_1_4">A SQL injection attack consists of insertion or “injection” of a SQL query via the input data from the client to the application. A successful SQL injection exploit can read sensitive data from the database, modify database data (Insert/Update/Delete), execute administration operations on the database (such as shutdown the DBMS), recover the content of a given file present on the DBMS file system and in some cases issue commands to the operating system. SQL injection attacks are a type of injection attack, in which SQL commands are injected into data-plane input in order to effect the execution of predefined SQL commands.</h3>
    <br> </div>
  <div class="">
    <h2 class="body_title_sub dot_white font_monts has_icon dot_mb_1">Objective</h2>
    <h3 class="font_mono dot_no_white dot_f14 l_h_1_4 dot_mb_2">There is personal information for about 100 persons stored in the DB. Pull out information for all the persons in 1 shot via Injection.</h3>
    <?php pushDotMessageWarning("Fake INFO. generated by <a class='dot_links' href='https://mockaroo.com/' target='blank'>MOCKAROO</a>");?>
    <h3 class="font_mono dot_no_white dot_f14 l_h_1_4 dot_mb_1 dot_mt_2">
      <?php 
          for($i=0;$i<16;$i++){
            echo "Injecting<br>";
          }
      ?>
    </h3>
    <?php 
          pushDotMessageInfo("Why just why?<br>Look for a cheatsheet?");
    ?>
    </div>
</body>